### Programming in GIS with Python 
 
### Universidad Nacional de Colombia

### Lecturer: Liliana Castillo Villamor

### 🧪Workshop 2: Exploring NumPy and pandas with Precipitation Data**

### 🎯 Learning Objectives
By completing this notebook, you will:
- Understand what a NumPy array is, and how to work with its attributes and operations.
- Learn how to manipulate real-world datasets using pandas Series and DataFrames.
- Perform transformations and handle missing data.
- Apply grouping and aggregation to summarize patterns in precipitation data.

# 1. Getting Started
Data used in all the workshops is avaliable at the following **[LINK](https://drive.google.com/drive/folders/1vt_uG7KxSQfRShpHpT8cEplAcO64jmPR?usp=sharing)**


In this first part, we’ll work with simulated precipitation data. To do this, we’ll use NumPy — a powerful Python library for numerical computing.

We’ll generate a series of random precipitation values using a statistical distribution that mimics daily rainfall (gamma distribution). This allows us to understand arrays before dealing with real-world files.enerate a series of random precipitation values using a statistical distribution that mimics daily rainfall (gamma distribution). This allows us to understand arrays before dealing with real-world files.

### 🧪 Why simulate rainfall using a gamma distribution?

The gamma distribution is often used to model rainfall amounts because:

- It generates continuous, non-negative values (like rainfall).
- It allows variability with a long tail — simulating heavy rain events.

We’ve created a NumPy array of 100 daily rainfall values (in millimters).
tools.


# 2.NumPy Arraysvalues).


## 2.1. What is a NumPy Array?

A NumPy array (`ndarray`) is a **homogeneous**, efficient container for numerical data. Compared to Python lists:

- Arrays are more compact and faster for mathematical operations.
- All elements have the same data type.
- They support **vectorized operations** (no need for `for` loops).
- Arrays are **mutable** (you can change their values).

Let’s explore the properties of the array we just created.


In [1]:
import numpy as np

# Simulate precipitation data (in mm)
np.random.seed(0)
valores = np.random.gamma(shape=2.0, scale=10.0, size=100)  # 100 simulated values

print(valores[:10])  # Preview first 10 values


[51.38829576 22.38480912 54.27132274  6.96586445 15.3693153  22.54930027
 28.54866955 18.28735053 23.07871921 21.35617034]


In [2]:
print(type(valores))   
print("Shape:", valores.shape)
print("Data type:", valores.dtype)
print("Dimensions:", valores.ndim)
print("Number of elements:", valores.size)

<class 'numpy.ndarray'>
Shape: (100,)
Data type: float64
Dimensions: 1
Number of elements: 100


### 🔍 Array attributes explained:

- `.shape`: Tuple showing the number of elements in each dimension.
- `.dtype`: Data type of the array (e.g., float64).
- `.ndim`: Number of dimensions (1D, 2D, 3D...).
- `.size`: Total number of elements in the array.

All of these are essential when working with geospatial and environmental data in NumPy.


#### 👩‍💻 Now it’s your turn

Write code below to:

1. Print the first 10 values of the array.
2. Print the last 5 values.
3. Print a slice from index 10 to 20.


In [10]:
# Your code here

print(valores[:10])
print(valores[95:100])
print(valores[10:21])
print(valores[-5:])


[51.38829576 22.38480912 54.27132274  6.96586445 15.3693153  22.54930027
 28.54866955 18.28735053 23.07871921 21.35617034]
[21.12933641  6.5627966  27.10542707  8.29747684  9.25548615]
[44.35287736 14.15590728  0.65982272 26.6090137  66.49635365  4.05894836
 45.31925473 43.74283733  7.6318726   1.9435868  38.12927328]
[21.12933641  6.5627966  27.10542707  8.29747684  9.25548615]


## 2.2. Vectorized Operations and Broadcasting

One of the main advantages of NumPy arrays is the ability to apply operations to entire arrays at once. This is known as **vectorization**, and it eliminates the need for explicit loops.on, **broadcasting** is a powerful feature that allows NumPy to perform operations between arrays of different shapes in a memory-efficient way.
ly.


In [12]:
# Let's work with a small array of precipitation values (in mm)
valores_sample = np.array([0.0, 5.5, 18.2, 25.0, 52.3])

# Add 10 mm to each value (simulating a bias correction)
valores_plus10 = valores_sample + 10

# Multiply each value by 2 (e.g., doubling the intensity)
valores_doble = valores_sample * 2

# Subtract the average precipitation from each value (centering)
media = valores_sample.mean()
valores_centrados = valores_sample - media

valores_sample, valores_plus10, valores_doble, valores_centrados


(array([ 0. ,  5.5, 18.2, 25. , 52.3]),
 array([10. , 15.5, 28.2, 35. , 62.3]),
 array([  0. ,  11. ,  36.4,  50. , 104.6]),
 array([-20.2, -14.7,  -2. ,   4.8,  32.1]))

### 🧮 What is broadcasting?

Broadcasting lets NumPy apply an operation between arrays of **different shapes**. In the examples above:

- `valores_sample` is a 1D array of shape (5,)
- `10` is a scalar (shape `()`), but NumPy **broadcasts** it to match the shape of the array

This mechanism avoids the need to manually replicate or reshape arrays, making code cleaner and more efficient.
ation.


In [13]:
# Broadcasting example: compare each value with a threshold
lluvia_moderada = valores_sample > 10
lluvia_moderada



array([False, False,  True,  True,  True])

### 💡 Example use case of broadcasting:

Let’s say we want to classify rainfall intensity into categories. We can do this using broadcasting and logical conditions:

- `valor < 1` → “Dry”
- `1 ≤ valor < 10` → “Light”
- `10 ≤ valor < 50` → “Moderate”
- `valor ≥ 50` → “Heavy”

Let’s use `np.select()` to apply this logic to our array.


In [ ]:
#This block of code classifies precipitation values into categories such as "Dry", "Light", "Moderate", and "Heavy". Let's break it down line by line:
# Define a list of Boolean conditions based on precipitation thresholds (in mm)
# Each condition is applied element-wise to the NumPy array `valores_sample`
condiciones = [
    valores_sample < 1,                              # Condition 1: values less than 1 mm → "Dry"
    (valores_sample >= 1) & (valores_sample < 10),  # Condition 2: between 1 (inclusive) and 10 (exclusive) → "Light"
    (valores_sample >= 10) & (valores_sample < 50), # Condition 3: between 10 and 50 → "Moderate"
    valores_sample >= 50                            # Condition 4: values 50 mm or more → "Heavy"
]

# Define the corresponding category labels for each condition
categorias = ["Dry", "Light", "Moderate", "Heavy"]

# Use np.select to assign a category to each value in `valores_sample`
# It checks each condition in order and applies the corresponding label from `categorias`
clasificacion = np.select(condiciones, categorias)

# Iterate through both `valores_sample` and the resulting `clasificacion` in parallel
# `zip()` pairs each value with its assigned category
for v, c in zip(valores_sample, clasificacion):
    # Print the precipitation value formatted with 1 decimal place, followed by its category
    print(f"{v:.1f} mm → {c}")



Lets do a vectorized computation of daily temperature range

In [14]:
# Arrays of daily maximum and minimum temperatures (in °C)
max_temp = np.array([30, 28, 26, 25, 27, 31, 29])
min_temp = np.array([18, 17, 16, 15, 16, 19, 18])

# Vectorized operation: subtract one array from another (same shape)
temp_range = max_temp - min_temp

print(temp_range)


[12 11 10 10 11 12 11]


#### 👩‍💻 Now it’s your turn

1. Use broadcasting to subtract 5 mm from each value in the array.
2. Create a new classification: flag values above 20 mm as "Extreme".


In [15]:
# Your code here
minus_five = max_temp -5
print(minus_five)

[25 23 21 20 22 26 24]


## 2.3. Universal Functions (ufuncs)

**ufuncs** are optimized, element-wise operations that NumPy provides for common mathematical tasks. They work seamlessly with arrays.

Examples:
- `np.sqrt(x)` → square root
- `np.log1p(x)` → natural log of (1 + x)
- `np.clip(x, min, max)` → restrict values within a range


In [ ]:
print("array of total values",valores)
print ("np.sqrt(valores[:5])",np.sqrt(valores[:5]))
print ("np.log1p(valores[:5])",np.log1p(valores[:5]))
print ("np.log1p(valores[:5])",np.clip(valores[:10], 0, 100))

### 👩‍💻 Now it’s your turn

Use NumPy ufuncs to:

1. Apply `np.exp()` to lastirst 5 values.
2. Compute the absolute difference between each value and 50 using `np.abs()`.


In [ ]:
# Your code here


## 🧠 Reflection Questions:
What is the benefit of broadcasting?

When might you use np.clip() in environmental analysis?


# 3. 🔎 Pandas: From Arrays to Tables
**pandas** is a Python library designed for working with **structured (tabular) data**. It provides two main data structures:

- `Series`: a **one-dimensional** labeled array (similar to a single column in a spreadsheet).
- `DataFrame`: a **two-dimensional** labeled table (like a spreadsheet or SQL table), where each column can hold different types of data.

pandas is essential in data science and geospatial analysis because it allows us to:
- Load data from files such as CSVs.
- Explore and summarize datasets.
- Clean and transform data efficiently.
- Perform statistical analysis and aggregations.
- Prepare data for visualization and

We begin by importing the pandas library and loading the precipitation dataset.modeling.


In [ ]:
import pandas as pd

# Load dataset
root_folder="C:/Users/Liliana/OneDrive - Universidad Nacional de Colombia/1_Periodos_Asignaturas/Cursos_2025_1/Programacion SIG/Talleres/"
precip = pd.read_csv(root_folder+"precipitacion.csv")
precip.head()

### 🧾 What does `.head()` do?
The `.head()` method displays the first 5 rows of the DataFrame.

**You can try:**
- `.head(10)` → First 10 rows
- `.tail()` → Last rows
- `.shape` → Number of rows and columns
- `.columns` → Column names
- `.info()` → Column types and missing values
- `.describe()` → Numeric summary

## 3.1. 🔍 Inspecting the Dataset
We will use pandas methods to understand the structure of the data:

- .shape: number of rows and columns

- .columns: list of column names

- .info(): overview of data types and missing values

- .describe(): statistical summary of numerical columns

In [ ]:
precip.describe()

In [ ]:

precip.info()

**How to interpret this :**

- The dataset has 8007 rows and 8 columns.

- The data types include integers, floats, and strings (object).

- The Fecha column needs to be converted to datetime.

### 🧠 What does `object` mean?

In `pandas`, the data type `object` is a **general-purpose placeholder**. It usually means:

- The column contains **text (strings)**.
- Or a **mix of different types** (e.g., numbers and strings).
- Or other Python objects like **lists, dictionaries**, etc.

In our dataset, all `object` columns (like `NombreEstacion`, `Unidad`, and `NivelAprobacion`) are meant to represent **text labels**, so we should convert them to the proper `string` type.


### 📚 Common `pandas` Data Types

| Dtype            | Description                        | Example             |
|------------------|------------------------------------|---------------------|
| `int64`          | Whole numbers                      | 42, 8007            |
| `float64`        | Decimal numbers                    | 5.6, 99.9           |
| `object`         | Generic type (often used for text) | `"LA VICTORIA"`     |
| `string`         | Explicit string data type          | `"BOGOTÁ"`          |
| `bool`           | Boolean (True/False)               | `True`, `False`     |
| `datetime64[ns]` | Date and time                      | `2024-07-01 00:00`  |


## 3.2. 🧩 Cleaning and Transforming Data

### ❓ Handling Missing Values

We check if any values missing:.sum()


In [ ]:
precip.isna().sum()

### 🔁 Replacing Values

Even if all rows are complete, you should be aware of incomplete or invalid values like "NA" strings or suspicious values such as 0 mm on rainy days.

In [ ]:
precip['NivelAprobacion'] = precip['NivelAprobacion'].replace('NA', 'No Data')


### 🔄 How to convert to `string` type

To ensure consistent handling of text columns, use `.astype("string")

For example:")


In [ ]:
precip['NombreEstacion'] = precip['NombreEstacion'].astype("string")

You can do the same for other text-based columns:

In [ ]:
precip['Unidad'] = precip['Unidad'].astype("string")
precip['NivelAprobacion'] = precip['NivelAprobacion'].astype("string")

### 🔤 String Operations
We can convert all station names to uppercase to ensure consistency:

In [ ]:
precip['NombreEstacion'] = precip['NombreEstacion'].str.upper()

#### 🧮 Working with Dates
Let’s convert 'Fecha' to datetime and extract year/month/day components:

In [ ]:
precip['Fecha'] = pd.to_datetime(precip['Fecha'], errors='coerce')
precip['Año'] = precip['Fecha'].dt.year
precip['Mes'] = precip['Fecha'].dt.month


#### 👩‍💻 Now it’s your turn:
- Create a column called Dia with the day of the month from 'Fecha'.

- Create a column called Intensidad with values 'Alta' if 'Valor' > 50', otherwise 'Normal'.


In [ ]:
# Your script here

### 🔁 Replacing and Renaming
Sometimes categorical values are inconsistent or unclear. You can use `.replace()` to standardize them, and `.rename()` to clarify column names.


In [ ]:
# Replace 'NA' in NivelAprobacion
precip['NivelAprobacion'] = precip['NivelAprobacion'].replace('NA', 'No Data')

# Rename the column 'Unidad' to 'UnidadMedida'
precip = precip.rename(columns={'Unidad': 'UnidadMedida'})


#### 👩‍💻 Now it’s your turn:
- Replace the value 'SIN DATO' in `'NivelAprobacion'` with `'Missing'`.
- Rename the column `'Parametro'` to `'TipoDato'`.


In [ ]:
# Your code here


### 🧮 Creating New Columns
You can create new columns by transforming existing ones. This is useful for categorizing, scaling, or engineering new features for analysis.

Let's add a column that:
- Converts `'Valor'` to integer mm values.
- Categorizes intensity based on a threshold.


In [ ]:
# Round precipitation values
precip['ValorEntero'] = precip['Valor'].round(0).astype(int)

# Create intensity category
precip['Intensidad'] = ['Alta' if x > 50 else 'Normal' for x in precip['Valor']]


#### 👩‍💻 Now it’s your turn:
- Create a column `'Valor_cm'` that converts mm to centimeters.
- Create a column `'TipoEvento'` where values > 100 are labeled `'Evento extremo'`, otherwise `'Evento común'`.



In [ ]:
# Your code here


## 3.3. 📊 Descriptive statistics and filtering

In [ ]:
precip['Valor'].mean()
precip['Valor'].describe()


## 3.4. Aggregation and Grouping

Aggregation allows us to summarize and analyze large volumes of data efficiently. In pandas, we use `.groupby()` to split the dataset into groups based on one or more keys (like station or year), and then we apply aggregation functions such as `mean()`, `min()`, `max()`, or `std()`.

This is especially useful in environmental datasets like precipitation, where we may want to understand:
- How rainfall varies **by station**
- How precipitation changes **over time** (e.g., by month or year)
- The **range and distribution** of rainfall values within a 
by StationLet’s group the data by station name and calculate the average recorded precipitation.tion:


In [ ]:
precip.groupby('NombreEstacion')['Valor'].mean().sort_values(ascending=False)


The previous line performs a grouped aggregation and sorting in the following steps:

`precip.groupby('NombreEstacion')`: Groups the dataset by the 'NombreEstacion' column — meaning all rows that share the same station name will be grouped together.

`['Valor'].mean()` :For each station group, calculates the average (mean) of the 'Valor' column, which contains precipitation values.

`.sort_values(ascending=False)`:Sorts the resulting average values from highest to lowest, so the stations with the highest mean precipitation appear at the top.

**This is useful to compare average rainfall across all stations in descending order.**

### 🔄 Multiple Aggregations

We can also compute several summary statistics at once by using `.agg()`.

This is useful when you want a more complete picture of variation within each group.


In [ ]:
precip.groupby('NombreEstacion')['Valor'].agg(['mean', 'min', 'max', 'std'])


### 👩‍💻 Now it’s your turn:
- Group by `'NombreEstacion'` and compute the **maximum precipitation**.
- Sort the results in ascending order.
- Group by `'NivelAprobacion'` and compute both the `mean` and `count` of `'Valor'`.
- Group by `'Variable'` and compute `min`, `max`, and `std`..
.



### 📆 Aggregating by Time
We can also aggregate data by **time components** like year or month to explore seasonality or trends over years.

Let’s group by `'Año'` and `'Mes'` and compute the monthly average precipitation across all stations.


In [ ]:
precip.groupby(['Año', 'Mes'])['Valor'].mean()

#### 👩‍💻 Now it’s your turn:
- Group by `'Año'` and calculate the total (`sum`) precipitation per year.
- Group by `'Mes'` and compute the standard deviation of `'Valor'`.
.



In [ ]:
# Your code here


## 3.5. 🧩 Basic Visualization with pandas and matplotlib

Visualizing aggregated data helps us understand trends and compare groups more intuitively. 

In pandas, we can use `.plot()` to quickly create basic charts from Series or DataFrames. These are powered by the `matplotlib` library.

Let's explore basic line and bar plots using the precipitation data.


### 📈 Line Plot: Annual Average Precipitation

Let’s visualize how average precipitation has changed **year by year**.


In [ ]:
import matplotlib.pyplot as plt

# Average precipitation by year
precip.groupby('Año')['Valor'].mean().plot(kind='line', marker='o', title='Average Annual Precipitation')
plt.xlabel('Year')
plt.ylabel('Precipitation (mm)')
plt.grid(True)
plt.tight_layout()
plt.show()


###  📊 Bar Plot: Monthly Mean Precipitation

Now let’s compare **average monthly precipitation** across all stations.


In [ ]:
precip.groupby('Mes')['Valor'].mean().plot(kind='bar', title='Average Monthly Precipitation')
plt.xlabel('Month')
plt.ylabel('Precipitation (mm)')
plt.grid(True)
plt.tight_layout()
plt.show()


#### 👩‍💻 Now it’s your turn:
- Create a line plot of **total precipitation per year**.
- Create a bar chart showing **standard deviation of precipitation per month**.


In [2]:
# Your code here
